groups:
  arm:
    operating_mode: position
    profile_type: time
    profile_velocity: 2.5
    profile_acceleration: 2.5
    torque_enable: true
singles:
  gripper:
    operating_mode: current_based_position
    profile_type: time
    profile_velocity: 2.5
    profile_acceleration: 2.5
    torque_enable: true
